Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Recorder Configuration
        Parameters:
          - RecordAll
          - IncludeGlobalResourceTypes
          - RecorderName
          - RecordingFrequency
          - RecordOverRide

      - Label:
          default: Over Rides
        Parameters:
          - Exclusions
          - ExcludeServices
          - ServicesOverride
          - OverRideFrequency

      - Label:
          default: Delivery Channel
        Parameters:
          - S3BucketName
          - DeliveryFrequency
          - EMail

Parameters:

  RecorderName:
    Type: String
    Default: Aws_config_base_recorder

  RecordAll:
    Type: String
    Description: Record all available Resources
    Default: true
    AllowedValues: 
       - true
       - false

  DeliveryFrequency:
    Description: Delivery frequency for the config to send data into Delivery Channel
    Type: String
    Default: Three_Hours
    AllowedValues:
      - One_Hour
      - Three_Hours
      - Six_Hours
      - Twelve_Hours
      - TwentyFour_Hours

  S3BucketName:
    Type: String
    Description: Enter a s3 bucket name to create


  IncludeGlobalResourceTypes:
    Type: String
    Description: Recorder will also record global resource types such as Aurora global data store
    Default: true
    AllowedValues: 
      - True
      - False

  Exclusions:
    Type: String
    Description: Exclude any specific resources from recording?
    Default: false
    AllowedValues: 
       - true
       - false

  RecordOverRide:
    Description: Are there any services to override the default recording frequency?
    Type: String
    Default: false
    AllowedValues: 
       - true
       - false

  ExcludeServices:
    Type: List<String>
    Description: List of Services to exclude from recording
    Default: <None>

  ServicesOverride:
    Type: List<String>
    Description: List of Services to set a different record frequency
    Default: <None>

  OverRideFrequency:
    Description: Recording frequency for mentioned list of services in ServicesOverride
    Type: String
    Default: None
    AllowedValues:
      - None
      - DAILY
      - CONTINUOUS

  RecordingFrequency:
      Type: String
      Default: CONTINUOUS
      AllowedValues:
        - CONTINUOUS
        - DAILY
  Email:
    Type: String
    Description: Email for SNS topic to send



Conditions:
  RecordALL:
    !And
      - !Equals [!Ref RecordAll, true]
      - !Equals [!Ref Exclusions, false]

  Custom: !Equals [!Ref RecordAll, false]

  OverrideEnabled: !Equals [!Ref RecordOverRide, true]

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName

  S3bucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AWSConfigBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub arn:${AWS::Partition}:s3:::${S3BucketName}

          - Sid: AWSConfigBucketDelivery
            Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub arn:${AWS::Partition}:s3:::${S3BucketName}/AWSLogs/${AWS::AccountId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ConfigTopic
      DisplayName: AWS Config Notification Topic

  ConfigSNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref Email
      Protocol: email
      TopicArn: !Ref SNSTopic

  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref SNSTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: Statement1
            Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action:
              - sns:Publish
              - sns:TagResource
            Resource: !Ref SNSTopic

  RecorderRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWS_ConfigRole

  Recorder:
    Type: AWS::Config::ConfigurationRecorder
    Condition: RecordALL
    Properties:
      Name: !Ref RecorderName
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResourceTypes: !Ref IncludeGlobalResourceTypes
        RecordingStrategy:
          UseOnly: ALL_SUPPORTED_RESOURCE_TYPES

      RecordingMode:
        RecordingFrequency: !Ref RecordingFrequency

        RecordingModeOverrides: !If
          - OverrideEnabled
          - - RecordingFrequency: !Ref OverRideFrequency
              ResourceTypes: !Ref ServicesOverride
          - !Ref AWS::NoValue

      RoleARN: !GetAtt RecorderRole.Arn

  RecorderCustom:
    Type: AWS::Config::ConfigurationRecorder
    Condition: Custom
    Properties:
      Name: !Ref RecorderName

      RecordingGroup:
        AllSupported: false
        ExclusionByResourceTypes:
          ResourceTypes: !Ref ExcludeServices
        IncludeGlobalResourceTypes: !Ref IncludeGlobalResourceTypes
        RecordingStrategy:
          UseOnly: EXCLUSION_BY_RESOURCE_TYPES

      RecordingMode:
        RecordingFrequency: !Ref RecordingFrequency

        RecordingModeOverrides: !If
          - OverrideEnabled
          - - RecordingFrequency: !Ref OverRideFrequency
              ResourceTypes: !Ref ServicesOverride
          - !Ref AWS::NoValue

      RoleARN: !GetAtt RecorderRole.Arn

  DeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    DependsOn: 
      - S3Bucket
    Properties:
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: !Ref DeliveryFrequency
      S3BucketName: !Ref S3BucketName
      SnsTopicARN: !Ref SNSTopic

  configRuleforSecurity:
    Type: AWS::Config::ConfigRule
    DependsOn:
            - DeliveryChannel
    Properties:
      ConfigRuleName: Security
      Description: Eni attached to Ec2
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Instance
          - AWS::EC2::SecurityGroup
      Source:
        Owner: AWS
        SourceIdentifier: EC2_SECURITY_GROUP_ATTACHED_TO_ENI
  
  configRuleforSecurityGroup:
    Type: AWS::Config::ConfigRule
    DependsOn:
            - DeliveryChannel
    Properties:
      ConfigRuleName: SecurityGroup
      Description: Open security group 
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::SecurityGroup
      Source:
        Owner: AWS
        SourceIdentifier: VPC_SG_OPEN_ONLY_TO_AUTHORIZED_PORTS
  
  configRuleforSecurityGroupUnauthorised:
    Type: AWS::Config::ConfigRule
    DependsOn:
            - DeliveryChannel
    Properties:
      ConfigRuleName: SecurityGroupUnauthorised
      Description: Open security group to unauthorised ports
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::SecurityGroup
      Source:
        Owner: AWS
        SourceIdentifier: VPC_SG_PORT_RESTRICTION_CHECK

  ConfigRuleForVolume:
    Type: AWS::Config::ConfigRule
    DependsOn:
            - DeliveryChannel
    Properties:
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Volume
          - AWS::EC2::Instance
      Source:
        Owner: AWS
        SourceIdentifier: EBS_IN_BACKUP_PLAN
              
              
  ConfigRuleforIamMfa:
    Type: AWS::Config::ConfigRule
    DependsOn:
            - DeliveryChannel
    Properties:
      Scope:
        ComplianceResourceTypes:
          - AWS::IAM::User
          - AWS::IAM::Policy
      Source:
        Owner: AWS
        SourceIdentifier: IAM_USER_MFA_ENABLED

  
  ConfigRuleRootMfaCheck:
       Type: AWS::Config::ConfigRule
       DependsOn:
            - DeliveryChannel
       Properties:
           ConfigRuleName: root-account-mfa-enabled
           Source:
             Owner: AWS
             SourceIdentifier: ROOT_ACCOUNT_MFA_ENABLED
  
  ConfigRuleIAMPolicyNoFullAdmin:
      Type: AWS::Config::ConfigRule
      DependsOn:
            - DeliveryChannel
      Properties:
          ConfigRuleName: iam-policy-no-statements-with-full-access
          Source:
              Owner: AWS
              SourceIdentifier: IAM_POLICY_NO_STATEMENTS_WITH_FULL_ACCESS

  ConfigRuleIAMPasswordPolicy:
      Type: AWS::Config::ConfigRule
      DependsOn:
            - DeliveryChannel
      Properties:
            ConfigRuleName: iam-password-policy
            Source:
               Owner: AWS
               SourceIdentifier: IAM_PASSWORD_POLICY
            InputParameters:
                RequireUppercaseCharacters: "true"
                RequireLowercaseCharacters: "true"
                RequireNumbers: "true"
                RequireSymbols: "true"
                MinimumPasswordLength: "14"
                PasswordReusePrevention: "24"
                MaxPasswordAge: "90"

  ConfigRuleAllowedAMIs:
     Type: AWS::Config::ConfigRule
     DependsOn:
            - DeliveryChannel
     Properties:
           ConfigRuleName: ec2-allowed-amis
           Source:
              Owner: AWS
              SourceIdentifier: EC2_INSTANCE_LAUNCHED_WITH_ALLOWED_AMI


  ConfigRuleSSMManaged:
      Type: AWS::Config::ConfigRule
      DependsOn:
            - DeliveryChannel
      Properties:
          ConfigRuleName: ec2-managed-by-ssm
          Source:
            Owner: AWS
            SourceIdentifier: EC2_INSTANCE_MANAGED_BY_SSM

  ConfigRuleSSHDisabled:
        Type: AWS::Config::ConfigRule
        DependsOn:
            - DeliveryChannel
        Properties:
          ConfigRuleName: restricted-ssh
          Source:
            Owner: AWS
            SourceIdentifier: INCOMING_SSH_DISABLED


  ConfigRuleRequiredTags:
        Type: AWS::Config::ConfigRule
        DependsOn:
            - DeliveryChannel
        Properties:
          ConfigRuleName: required-tags
          Scope:
            ComplianceResourceTypes:
              - AWS::EC2::Instance
              - AWS::S3::Bucket
              - AWS::EBS::Volume
          Source:
            Owner: AWS
            SourceIdentifier: REQUIRED_TAGS
          InputParameters:
            tag1Key: Environment
            tag2Key: Owner
        